### ISSUE TITLE
The main convert method do not use ConvertAPI naming convention

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-go#6]
The main convert method do not use ConvertAPI naming convention, instead of `convertapi.ConvDef` should be `convertapi.Convert`, the same applies to snippets.

https://github.com/ConvertAPI/convertapi-go/blob/a822cefe0641ce45c4acd7a59c8b4f1266aeb196/convert.go#L12

**Comment by JonasJasas** [comment]
By design. As GO has no default values for parameters nor function overloads so this function takes less arguments and replaces with the defalt values.

**Comment by tomasr78** [comment]
When maybe we could swap names? The full method could be ConvDef and smaller alternate version Convert? Which version would be used more often?

**Comment by JonasJasas** [comment]
Fixing issue that don't exist would introduce breaking changes.
