### ISSUE TITLE
Introduce alternative converter parameter in conversion method

### ISSUE THREAD

**Issue by tomasr78** [ConvertAPI/convertapi-go#7]
Some formats have several converters, for example `docx` to `pdf` has three of them listed below.
It should be a possibility to set up an alternative converter from the library in the Convert method.

https://v2.convertapi.com/convert/docx/to/pdf
https://v2.convertapi.com/convert/docx/to/pdf/converter/openoffice
https://v2.convertapi.com/convert/docx/to/pdf/converter/printer

This is only an example of a convert method on how it could implement alternative converters.

Default method

```
convertapi.ConvDef("docx", "pdf",
    param.NewPath("File", "/path/to/my_file.docx", nil),
).ToPath("/path/to/result/dir");

```
with alternative converter

```
convertapi.ConvDef("docx", "pdf","openoffice"
    param.NewPath("File", "/path/to/my_file.docx", nil),
).ToPath("/path/to/result/dir");
```

**Comment by JonasJasas** [comment]
Done
